### ISSUE TITLE
export 'IMetadata' was not found in 'kaop-ts'

### ISSUE THREAD

**Issue by musti2** [k1r0s/kaop-ts#5] opened 2017-06-02 00:01 UTC
Hi,

I am facing this error with Angular 4.

export 'IMetadata' was not found in 'kaop-ts'

![angular warning](http://i.imgur.com/kBg020O.png)

```Javascript
import { Injectable } from '@angular/core'
import { AdvicePool, adviceMetadata, IMetadata } from 'kaop-ts'

@Injectable()
export class LogAspect extends AdvicePool {
  static log(@adviceMetadata meta: IMetadata) {
    console.log('Called: ', meta.target)
    console.log('Args: ', meta.args)
  }
}
```

**Comment by k1r0s** [comment] 2017-06-02 07:29
Hi there,

I see a typo were as 'adviceMetadata' is miss spelled.

Could you please check this? Thanks!

**Comment by k1r0s** [comment] 2017-06-02 07:33
By the way log method is 'static' so there is no need to apply 'Injectable()' :)

**Comment by k1r0s** [comment] 2017-06-02 08:06
`export 'IMetadata' was not found in 'kaop-ts'` error is due Angular is trying to inject `meta` as an instance of IMetadata which is not declared as a dependency. 

to retrieve method metadata you don't need `@Injectable()`

**Comment by musti2** [comment] 2017-06-02 08:49
Hey there,

Firstly, appreciate your prompt response!

**The Logging aspect works as expected**. My IDE shows no errors either, however, in the browser is where i see the error. 

Here is the full implementation (without @Injectable :)) -

```
import { AdvicePool, adviceMetadata, IMetadata } from 'kaop-ts'

export class LoggingAspect extends AdvicePool {
    static log( @adviceMetadata meta: IMetadata) {
        console.log('Called: ', meta.target)
        console.log('Args: ', meta.args)
    }
}
```

And the service method i am injecting it to is:
```
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs/Observable'

// kaop imports
import { beforeMethod } from 'kaop-ts';
import { LogAspect } from '../sample-advice';

import 'rxjs/add/operator/toPromise';

@Injectable
export class MyService {

    constructor(private http: Http) { }

    @beforeMethod(LoggingAspect.log)
    httpGetRequest(url: string): Promise<Response> {
        return this.http.get(url)
            .toPromise().then(...)
    }
}
```

I also tried the example on the readme, with the same error in the browser console:

```
    static log( @adviceMetadata metadata: IMetadata) {
        console.log(`${metadata.target.name}::${metadata.propertyKey}()`) // class and method name
        console.log(`called with arguments: `)
        console.log(metadata.args) // function arguments
        console.log(`output a result of: `)
        console.log(metadata.result) // returned value
    }
```

**Comment by k1r0s** [comment] 2017-06-02 09:08
So, advice is working but u got an error anyway? :\ seems weird

Hold on, I'm gonna test this

**Comment by alexjoverm** [comment] 2017-06-02 09:32
Hi @musti2!

> in the browser is where i see the error

How are you running it? Can you provide the exact **steps** in order to reproduce it? That'd help a lot

**Comment by k1r0s** [comment] 2017-06-02 09:47
Hi again @musti2 

I have tested your use case, at least with the provided info

You should not place @Injectable in advice container (aka `LoggingAspect`) since advices should be static and its arguments are not provided by any DI system. This means you don't need Angular to care about how advices have access to parameters.

An advice (for example `LoggingAspect.log`) could access to:

- method arguments
- class name
- method name
- method returned value
- advice arguments

![image](http://i.imgur.com/Zuqky6u.png)

**Comment by k1r0s** [comment] 2017-06-02 09:53
if you declare `@Injectable()` on advice container Angular will try to look for dependencies. But this not an issue or bug. 

![angular warning](http://i.imgur.com/kBg020O.png)

**Comment by k1r0s** [comment] 2017-06-02 10:01
@musti2 is it correct for you? I'm able to get rid of warning by removing `@Injectable()`

**Comment by k1r0s** [comment] 2017-06-02 10:05
I think Angular nor this library is the cause of this :\ gonna seek a solution

**Comment by alexjoverm** [comment] 2017-06-02 10:09
@musti2 @k1r0s I found the issue, we can fix by changing `IMetadata` to an empty class, instead of an interface.

The problem is in TypeScript + Webpack side, not in ours, but apparently it's a real issue. When exporting code + interfaces in the same file, Webpack treats it as CJS modules instead of ESM, causing compile-time code (interfaces) to be looked up. Of course this is removed after all by TypeScript, so that's why it's a warning and things keep running.

There are 2 solutions: either split exports in separate files (one for code and another for interfaces) or rewrite the exported interfaces (IMetadata) as an empty class. Keep in mind empty classes, used as types (no `new` invoked) in TypeScript are removed when compiled, just as interfaces, so no junk code is generated.

More info on https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897

**Comment by k1r0s** [comment] 2017-06-02 10:25
Enough arguments by @alexjoverm to close this, thanks mate

**Closed by k1r0s** 2017-06-02 10:25 UTC
Labels: need more info, not a bug

**Comment by alexjoverm** [comment] 2017-06-02 11:17
@k1r0s I think it was too early to close, since we didn't provide a final solution.

I've been investigating. As you could have seen in angular/angular-cli#2034 (comment), the issue have implications on Webpack, TypeScript and Angular, so prob the issue will remain for a time, and is not in our side. Is not too important anyway since is a warning.

Anyway, I've tried several things from `kaop-ts` side, and there is nothing we can do. The best workaround I found is, in the angular app re-exporting the interface from an **inteface-only** file (very important, don't mix interfaces with variables, const, classes or functions in that file):

```typescript
// app/interfaces.ts
...
export { IMetadata } from 'kaop-ts';
...
```

```typescript
// app/logging-aspect.ts

import { adviceMetadata, AdvicePool } from 'kaop-ts'
import { IMetadata } from './interfaces' // Import from here instead

class LoggingAspect extends AdvicePool {
    static log( @adviceMetadata meta: IMetadata) {
        console.log('Called: ', meta.target);
        console.log('Args: ', meta.args);
    }
}
```

That will remove the warnings.

@k1r0s I'd suggest to add this case to a _Troubleshooting_ section in the Readme. Then is more visible for the angular users

**Comment by k1r0s** [comment] 2017-06-02 11:22
Agree. Best contributor ever

**Comment by alexjoverm** [comment] 2017-06-02 11:33
Thanks to @musti2! We learnt something new today

**Comment by k1r0s** [comment] 2017-06-02 11:49
Another painless workarround

![export not found](http://i.imgur.com/rlqD0TJ.png)

More info
https://github.com/angular/angular-cli/issues/2034#issuecomment-260976971

**Comment by musti2** [comment] 2017-06-02 11:58
Thanks guys! Appreciate it.

The workaround does the trick.
