### ISSUE TITLE
metadata is undefined (Babel)

### ISSUE THREAD

**Issue by liangzr** [k1r0s/kaop-ts#9] opened 2017-07-20 06:45 UTC
I create a simple advice just like [Get Started](https://k1r0s.github.io/kaop-ts/#get-started), but advices can't find metadata.
- simple react demo project
- kaop-ts v1.2.0

App.js
```
import React, {Component} from 'react';
import logo from './logo.svg';
import './App.css';
import {afterMethod} from 'kaop-ts'
import {MyAdvices} from './MyAdvices'

class App extends Component {

  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this);
  }

  @afterMethod(MyAdvices.doubleResult)
  handleClick() {
    alert('You Click It!');
  }

  render() {
    return (
      <div className="App">
        <div className="App-header" onClick={this.handleClick}>
          <img src={logo} className="App-logo" alt="logo"/>
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit
          <code>src/App.js</code>
          and save to reload.
        </p>
      </div>
    );
  }
}

export default App;

```

MyAdvices.js
```
import { AdvicePool, adviceMetadata } from 'kaop-ts'

export class MyAdvices extends AdvicePool {
  static doubleResult (@adviceMetadata metadata) {
    console.log(metadata);     // always output undefined here
  }
}
```

**Comment by k1r0s** [comment] 2017-07-20 07:12
Hi there! Thanks for oppening the issue. 

The problem is that you're overriding method `handleClick`  in your constructor by assigning the context: 

```javascript
  constructor(props) {
    super(props);
    this.handleClick = this.handleClick.bind(this); // avoid
  }
```

You should do this instead, in order to keep method behavior: 

```jsx
 <div className="App-header" onClick={this.handleClick.bind(this)}>
```

**Comment by liangzr** [comment] 2017-07-20 09:51
@k1r0s Thanks for reply
I modify handleClick method jusk like you did，but it's useless. I use babel for ES7 decorator in my code without typescript.

MyAdvices.js
```
import { AdvicePool, adviceMetadata } from 'kaop-ts'

export class MyAdvices extends AdvicePool {
  static doubleResult (@adviceMetadata metadata) {
    console.log(metadata);     // always output undefined here
  }
}
```
After transform it with babel-cli, I can't find anything about `adviceMetadata` and `decorator`, maybe they disappeared when transformation?

After transform, partial code
```
var MyAdvices = exports.MyAdvices = function (_AdvicePool) {
  _inherits(MyAdvices, _AdvicePool);

  function MyAdvices() {
    _classCallCheck(this, MyAdvices);

    return _possibleConstructorReturn(this, (MyAdvices.__proto__ || Object.getPrototypeOf(MyAdvices)).apply(this, arguments));
  }

  _createClass(MyAdvices, null, [{
    key: 'doubleResult',
    value: function doubleResult(metadata) {
      console.log(metadata);
    }
  }]);

  return MyAdvices;
}(_kaopTs.AdvicePool);
```

**Comment by k1r0s** [comment] 2017-07-20 10:09
I have to check this in deep. 

**This lib isn't coded against babel since they dropped support for decorators some time ago ..**

Please share your package.json in order to test it. Thanks!

**Comment by liangzr** [comment] 2017-07-20 10:31
At first I added `kaop-ts` for my project and configrue babel with webpack, but it doesn't work with the same bug.So I create a simple demo by `create-react-app`, and use `babel-cli` to transform `App.js` and `MyAdvices.js` manually.
  
package.json
```
{
  "name": "aspect-demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "kaop-ts": "^1.2.0",
    "lodash": "^4.17.4",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "chai": "^4.1.0",
    "mocha": "^3.4.2",
    "react-scripts": "1.0.10",
    "sinon": "^2.3.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

```
.babelrc
```
{
    "presets": [
      "latest",
      "react",
      "stage-2"
    ],
    "plugins": ["transform-decorators-legacy"]
  }
```

**Comment by k1r0s** [comment] 2017-07-23 20:27
Hi, main problem with babel is about param decorators. Typescript implemented this some time ago. While babel firstly drop support because this feature wasn't fully included in decorators proposal.. (param decorators wasn't included initially). More info: https://github.com/babel/babel/issues/1301

And now are working to implement that feature: https://github.com/babel/proposals/issues/13

There are so call plugins to enable param decorators in babel but none of them worked for me in babel. 

I'll keep an eye on this, but I recommend to use this library with typescript. 

There is a JS vanilla version https://github.com/k1r0s/kaop which provides AOP tools in browsers world (ES5)

That's all :(

Hope @babel keep working on this

**Comment by liangzr** [comment] 2017-07-24 02:31
Thanks a lot @k1r0s ,

It is difficult to replace the whole project into typescript, but I wirte advices files use typescript (that I learned just last weekend :P) according to your suggestion, use babel for other `.js` files,  it works fine now!

I also will keep an eye on this, thanks for you libarary!

**Comment by k1r0s** [comment] 2017-07-24 05:27
Nice. Hope Babel keep pushing decorators feature

Any doubts give me a touch :)

I think we can close this issue. Thanks a lot

**Closed by k1r0s** 2017-07-24 05:27 UTC
Labels: feature

**Comment by k1r0s** [comment] 2017-07-30 22:24
Hey @liangzr, checkout last release :)

**Comment by liangzr** [comment] 2017-08-10 08:30
@k1r0s gread job! 

Although I prefer to use typescript now, but there are a lot of people use original js，which is very useful for them.

**Comment by k1r0s** [comment] 2017-08-11 11:05
Nice if you take that decision! Typescript is wonderful
